### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by hugosoli** [vaxerski/ZoomWebcamFix#2]
Hi, I have zoom version 5, and the binary break when I try to run it.
Any idea if compiling would make it work?
same issue than here
[https://obsproject.com/forum/threads/obs-virtualcam-not-working-with-zoom.117487/post-447462](url)

**Comment by vaxerski** [comment]
Oh I thought that zoom fixed the issue with an update a while ago, I'll dig into that right away

**Comment by vaxerski** [comment]
Released a fix, try now.

If you're still crashing open a new issue with reproducible steps and system information (os version), cuz I couldn't really reproduce the issue.
